// MizLang

def expr = 1 + 2 * 3.5 as u8

def u = undefined

def pi = 3.14

def pi = 314e-2

def a = 12345

def h = 0xABCD

def b = 0b1010

def s = "abcde"

def s = ""

def l = {a, b, c}

def l = { a,
    b

    ,

    c
}

def l = {}

def foo = fn() void {}

def foo = fn(a: i32, b: i32) i32 {}

def foo = fn() void {
    def c = undefined

    var x: i32 = undefined

    return x
    return
}

def signature = sig(T1, T2, T3) T

def ptr = *void

def slice = []T

def array = [N]T

def s = struct { p: T.name.name }

def Player = struct {
    pub pos: struct { x: i32, y: i32 },
    pub name: []u8,

    def Position = typeof(pos),

    def move = fn(self: *Self) void {
        return self

        g()

        if x() {
            x()
            loop {
                g()
                break
                continue
            }
        } else {

        }
    },

    def kek = sig(u8) void, // may be trailing comma
}